# Numpy

In [8]:
!python -m pip install numpy==1.18.5

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [9]:
l = range(1000000)

In [1]:
import numpy as np

In [12]:
d = np.arange(1000000)

In [13]:
%time for i in range(1, 10): r = [x * 2 for x in l]

Wall time: 1.3 s


In [14]:
%time for i in range(1, 10): r = d * 2

Wall time: 70 ms


## NDArray Object

In [15]:
x = np.zeros((4, 4))

In [16]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.empty((7,7))

array([[1.08355094e-311, 1.08354080e-311, 1.32937549e-311,
        9.43296199e-314, 6.48324739e+149, 5.02620677e+180,
        6.09964693e+149],
       [1.99680657e-268, 1.82160028e+185, 2.98233776e-308,
        1.33360299e+241, 5.13098582e-311, 8.31833568e-273,
        1.79209176e-313],
       [3.12140488e-308, 1.33360294e+241, 7.30390951e-311,
        2.83058296e-234, 3.48968839e-313, 2.70420353e-308,
        1.33360297e+241],
       [1.65388352e-310, 3.27759114e-157, 4.97508544e-313,
        4.85213860e-308, 1.33360301e+241, 1.43659115e-310,
        6.04608851e-138],
       [7.73367997e-313, 8.18974939e-308, 1.33360311e+241,
        2.52305300e-310, 3.06836125e+257, 8.73990239e+245,
        1.09384909e-303],
       [5.48094825e-294, 1.18499229e-303, 4.30738342e-294,
        5.48248398e-294, 4.80808152e-058, 1.29877292e+010,
        1.15290402e+280],
       [7.35554215e-063, 2.07040111e-048, 1.63848763e-019,
        1.68576902e-310, 1.63822344e-019, 1.74009211e-310,
        0.00000000

In [19]:
l = [1, 4, 5, 7]

In [20]:
np.array(l)

array([1, 4, 5, 7])

In [25]:
x = np.arange(1, 100, 10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [26]:
x.shape

(10,)

In [27]:
x = np.zeros((10, 10))

In [28]:
x.shape

(10, 10)

In [29]:
y = x.reshape((2, 2, 5, 5))

In [30]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [31]:
y.dtype

dtype('float64')

In [32]:
y.ndim

4

## Arithematic Operations on NDArray
### Vectorization

In [3]:
a = np.random.randn((10))

In [4]:
b = np.random.randn((10))

In [5]:
a

array([-0.36018995,  0.84052896,  1.42454947,  0.21560766, -0.46135455,
        0.52756614, -0.06255007,  2.83535006,  0.00994544,  0.00453911])

In [6]:
b

array([ 1.92351974, -1.28153515, -0.62164424,  0.56742139, -1.92855576,
       -0.56685825, -0.23735554,  1.68844012,  0.74864082, -1.46328416])

In [7]:
a + b

array([ 1.56332979, -0.44100619,  0.80290523,  0.78302905, -2.38991031,
       -0.03929211, -0.29990561,  4.52379018,  0.75858627, -1.45874505])

In [8]:
2 * a

array([-0.7203799 ,  1.68105791,  2.84909894,  0.43121533, -0.92270911,
        1.05513228, -0.12510014,  5.67070011,  0.01989089,  0.00907822])

In [9]:
1 / a

array([ -2.77631287,   1.18972701,   0.70197632,   4.63805407,
        -2.16753035,   1.89549693, -15.98719288,   0.35269014,
       100.54854542, 220.30755787])

In [10]:
a > 0

array([False,  True,  True,  True, False,  True, False,  True,  True,
        True])

In [11]:
# Get elements of array 'a' which are greater than 0
a[a > 0]

array([0.84052896, 1.42454947, 0.21560766, 0.52756614, 2.83535006,
       0.00994544, 0.00453911])

In [12]:
# Get elements of array 'a' which are than 0
a[a < 0]

array([-0.36018995, -0.46135455, -0.06255007])

## Indexing and Slicing

### Indexing

In [13]:
x = np.array([1, 7, 9, 8, 5])

In [14]:
x[4]

5

### Boolean Indexing

In [15]:
x[x > 5]

array([7, 9, 8])

### Fancy Indexing

In [16]:
x[[2, 1]]

array([9, 7])

In [20]:
x = np.random.randn(10, 10)

In [21]:
x

array([[ 0.61938065, -0.57371264, -1.96696813, -0.01784   ,  0.76074584,
         0.82365491,  0.14630188, -0.67683979, -0.55525512,  0.7370304 ],
       [-0.34828747, -0.14029484,  1.20573718, -1.22047834, -0.25587975,
        -1.48049347,  0.38931898,  0.1146111 , -0.31134017,  0.55872526],
       [ 0.77562353, -0.1389184 , -0.15049798, -1.5825326 ,  0.19645727,
        -1.39192992,  0.49995779, -0.48997406, -0.08901307,  0.39182931],
       [ 0.55091213, -0.88463326, -1.30598587,  0.32986163, -0.29962839,
        -2.48559842, -0.52977883, -1.332896  ,  1.38155673,  2.22044049],
       [ 0.06250199, -0.93051414, -2.29802816,  0.62718355, -1.46558878,
        -1.33871727, -1.11350489, -0.37189065,  1.4057929 , -0.16782305],
       [ 0.12145923,  0.50761919,  0.79472173, -0.00958051,  1.19193222,
         0.57439308, -0.47398999,  0.84532092, -0.6536653 , -1.36019715],
       [-0.32985974, -0.96498247,  0.235543  , -0.53909651,  0.37125131,
        -1.00127701,  0.13070128, -0.74462208

In [22]:
# Access first row
x[0]

array([ 0.61938065, -0.57371264, -1.96696813, -0.01784   ,  0.76074584,
        0.82365491,  0.14630188, -0.67683979, -0.55525512,  0.7370304 ])

In [24]:
# Access 1st row, 5th column
x[0][4]

0.7607458357862285

### Slicing

In [26]:
# Access odd values x[row_start:row_end:step, column_start:column_end:step]
x[1:10:2]

array([[-0.34828747, -0.14029484,  1.20573718, -1.22047834, -0.25587975,
        -1.48049347,  0.38931898,  0.1146111 , -0.31134017,  0.55872526],
       [ 0.55091213, -0.88463326, -1.30598587,  0.32986163, -0.29962839,
        -2.48559842, -0.52977883, -1.332896  ,  1.38155673,  2.22044049],
       [ 0.12145923,  0.50761919,  0.79472173, -0.00958051,  1.19193222,
         0.57439308, -0.47398999,  0.84532092, -0.6536653 , -1.36019715],
       [ 0.39597758, -1.35935583, -0.99005948, -1.72674362, -1.31525707,
        -1.83626888,  0.44972823,  0.46853528,  0.47396793,  0.87368729],
       [-0.60692504, -0.82555692, -0.1771334 , -1.92498714, -0.44776753,
        -0.37017214,  0.19317415,  1.15117979, -0.12181572,  0.14299324]])

In [27]:
# Access first 4 columns
x[::, 0:4]

array([[ 0.61938065, -0.57371264, -1.96696813, -0.01784   ],
       [-0.34828747, -0.14029484,  1.20573718, -1.22047834],
       [ 0.77562353, -0.1389184 , -0.15049798, -1.5825326 ],
       [ 0.55091213, -0.88463326, -1.30598587,  0.32986163],
       [ 0.06250199, -0.93051414, -2.29802816,  0.62718355],
       [ 0.12145923,  0.50761919,  0.79472173, -0.00958051],
       [-0.32985974, -0.96498247,  0.235543  , -0.53909651],
       [ 0.39597758, -1.35935583, -0.99005948, -1.72674362],
       [ 0.12763684, -0.65857562, -0.57187602,  0.38654562],
       [-0.60692504, -0.82555692, -0.1771334 , -1.92498714]])

In [28]:
x = np.ones((5, 5))

In [29]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
# Replace values in the array to 0 except for the first row, last row, first column and last column
x[1:-1, 1:-1] = 0

In [32]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Element-wise array functions

In [4]:
x = np.array([10, 9, 8, 6, 11])

In [42]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [43]:
np.power(x, 2)

array([100,  81,  64,  36, 121], dtype=int32)

In [1]:
y = [7, 1, 2, 3, -1]

In [5]:
np.maximum(x, y)

array([10,  9,  8,  6, 11])

## NP Where

In [2]:
salary = np.array([0, -1, 100000, 500000])

In [3]:
np.where(salary <= 0, 25000, salary)

array([ 25000,  25000, 100000, 500000])

In [4]:
np.where(salary <= 0, 'Not Ok', 'Ok')

array(['Not Ok', 'Not Ok', 'Ok', 'Ok'], dtype='<U6')

### Mathematical and Statistical Methods

In [5]:
x = np.array([10, 9, 7, 10, 7])

In [6]:
x.mean()

8.6

In [7]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [8]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [9]:
y = x > 6

In [10]:
y

array([ True,  True,  True,  True,  True])

In [11]:
y.sum()

5

In [13]:
y.any()

True

In [14]:
y.all()

True

In [15]:
y = x > 7

In [16]:
y

array([ True,  True, False,  True, False])

In [17]:
y.sum()

3

In [18]:
y.any()

True

In [19]:
y.all()

False

In [20]:
x

array([10,  9,  7, 10,  7])

In [21]:
x.sort()

In [22]:
x

array([ 7,  7,  9, 10, 10])

In [25]:
np.unique(x)

array([ 7,  9, 10])

## File Input and Output

In [51]:
x = [1, 4, 5, 7]

In [52]:
y = [8, 7, 9]

In [53]:
np.save('testx', x)

In [54]:
loadx = np.load('testx.npy')

In [55]:
loadx

array([1, 4, 5, 7])

In [56]:
np.savez('testxy', x, y)

In [57]:
loadxy = np.load('testxy.npz')

In [61]:
loadxy

In [63]:
# loadxy['x']
loadxy['arr_0']

array([1, 4, 5, 7])

## Linear Algebra Operations

In [67]:
x = np.random.rand(3, 2)

In [66]:
y = np.random.rand(2, 3)

In [68]:
x.dot(y)

array([[1.41906471, 1.00354915, 1.04678618],
       [1.37171771, 1.05856534, 1.03244507],
       [0.89183109, 0.8422731 , 0.70708025]])

In [69]:
x.transpose()

array([[0.985953  , 0.73581334, 0.10026539],
       [0.82619666, 0.99406491, 0.98646559]])

In [70]:
x.trace()

1.98001791450335

## Pseudo Random Number Generator

In [71]:
np.random.seed(7)

In [72]:
np.random.normal(size = (3, 3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [76]:
np.random.uniform(size = (3, 3))

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992]])

# Advanced Array Manipulations

## Reshape

In [78]:
x = np.random.randn(4, 5)

In [79]:
x

array([[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222],
       [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655],
       [-0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936],
       [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088]])

In [80]:
x.reshape((2, 2, 5))

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655]],

       [[-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [81]:
x.reshape((2, 2, 5), order = 'F')

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936]],

       [[-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [82]:
x.reshape((2, 2, -1))

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655]],

       [[-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [83]:
x

array([[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222],
       [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655],
       [-0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936],
       [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088]])

In [84]:
x.ravel()

array([ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655,
       -0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936,
       -2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088])

In [85]:
x.flatten()

array([ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655,
       -0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936,
       -2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088])

## Concatenate

Takes a sequence (tuple, list, etc) of arrays and joins them together in order along the input axis

In [86]:
x = [[1, 3, 5], [7, 9, 0]]

In [87]:
arr1 = np.array(x)

In [88]:
y = [[11, 13, 15], [17, 19, 10]]

In [89]:
arr2 = np.array(y)

In [90]:
np.concatenate((arr1, arr2), axis = 0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [91]:
np.concatenate((arr1, arr2), axis = 1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [92]:
np.vstack((arr1, arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [93]:
np.hstack((arr1, arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

## Split

In [94]:
x = [1, 4, 5, 6, 7, 9, 1, 4]

In [95]:
d = np.array(x)

In [96]:
np.split(d, [2, 5])

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [97]:
x = [[1, 4, 5, 6, 7, 9, 1, 4], [11, 14, 15, 16, 17, 19, 11, 14]]

In [98]:
d = np.array(x)

In [99]:
np.split(d, [4, 6], axis = 1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]),
 array([[ 7,  9],
        [17, 19]]),
 array([[ 1,  4],
        [11, 14]])]

In [101]:
np.split(d, [1], axis = 0)

[array([[1, 4, 5, 6, 7, 9, 1, 4]]), array([[11, 14, 15, 16, 17, 19, 11, 14]])]

## Tile and Repeat

Repeat replicates each element in an array some number of times, producing a larger array,if you pass an array of integers, each element can be repeated a different number of times

Tile is a shortcut for stacking copies of an array along an axis

In [102]:
d = np.array([1, 5, 7, 8])

In [103]:
np.repeat(d, 3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [106]:
np.tile(d, 2)

array([1, 5, 7, 8, 1, 5, 7, 8])